### ISSUE TITLE
Rights to use plugin 

### ISSUE THREAD

**Issue by GoodGameMesti** [Ben12345rocks/AylaChat#18]
Hello, I downloaded today your chat with spigot and the topic is not found law which are necessary to give players so that they could write in the chat. Just wanted to ask where you can translate your plugin? I just didn't find the "message" file . And the last question , whether it is possible to make in a plugin that prefixes were taken from PermissionEx ? Sorry if there are a lot of errors in the text, I communicate with the help of an interpreter in the browser and thank you for your help :)

**Comment by Ben12345rocks** [comment]
1. Topic of law? I think that got lost in translation? You the permissions for players?
2. Look in Config.yml, most options should be there.
3. Yeah, that's possible. Just use placeholderapi placeholders.

**Comment by GoodGameMesti** [comment]
Hello , not quite understandable that you wrote under point # 1, interpreters .. :)

**Comment by Ben12345rocks** [comment]
I'm not sure either. /aylachat perms?
That what you need?

**Comment by GoodGameMesti** [comment]
Yes , Yes . Need permission to players so they can chat in the thread on the spigot website do not have them unfortunately.

**Comment by Ben12345rocks** [comment]
Are you all good now?
